### ISSUE TITLE
rss feed, web server headers

### ISSUE THREAD

**Issue by realgeek** [rsivapr/DataTau-Issues#4]
When trying to add the DataTau rss feed to my feed reader, I get an error message. A very helpful person on their github account ( @mkresin https://github.com/miniflux/miniflux/issues/367#issuecomment-96671522 ) pointed out that the webserver hosting the RSS feed is sending non-compliant line breaks in the headers. Is this something you could take a look at?

**Comment by rsivapr** [comment]
Hey @realgeek. 
Thanks for letting me know and sorry I haven't had time to look into this. We are looking into giving DT a makeover and I'll look into this issue then. Closing this issue since it looks like the other project fixed the issue you were facing.
